volumes:
  cache_data: null

services:
  framepack:
    build:
      context: ../
      dockerfile: runpod.dockerfile
      args:
        EXT_PARALLEL: 1
        MAX_JOBS: 1
        CMAKE_BUILD_PARALLEL_LEVEL: 1
    volumes:
      - cache_data:/runpod-volume
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "200k"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]