name: "Publish to Docker registry"
description: "Publish an image/tags to a Docker registry"
inputs:
  username:
    description: "Docker registry account username"
    required: true
  password:
    description: "Docker registry account password"
    required: true
  image_name:
    description: "Docker image name"
    required: true
  branch:
    description: "Repository branch this image is built from"
    required: true
  commit_sha:
    description: "SHA hash of the commit that triggered this publish"
    required: true
  cuda_version:
    description: "CUDA version number to build for"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_name }}
    - name: Trim Commit SHA
      uses: 2428392/gh-truncate-string-action@v1
      id: trimCommitSha
      with:
        stringToTruncate: "${{ inputs.commit_sha }}"
        maxLength: 8
    - name: Trim CUDA version
      uses: 2428392/gh-truncate-string-action@v1
      id: trimCudaVersion
      with:
        stringToTruncate: "${{ inputs.cuda_version }}"
        maxLength: 4
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: Dockerfile
        tags: |
          ${{ inputs.image_name }}:cuda${{ steps.trimCudaVersion.outputs.string }}-latest${{ inputs.branch == 'main' && '' || format('-{0}', inputs.branch) }}
          ${{ inputs.image_name }}:cuda${{ steps.trimCudaVersion.outputs.string }}-${{ steps.trimCommitSha.outputs.string }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          CUDA_VERSION=${{ inputs.cuda_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
