name: framepack_devcontainer

volumes:
  cache_data: null

services:
  ubuntu:
    # `cudnn-devel` is required to compile `flash-attn` and others.
    image: nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
    environment:
      - HF_HOME=/cache-volume
      - UV_CACHE_DIR=/cache-volume/uv
      - FRAMEPACK_HOME=/cache-volume/framepack
    volumes:
      - ..:/workspace
      - cache_data:/cache-volume
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
