name: Development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - diffusers_helper/**
      - local_types/**
      - modules/**
      - utils/**
      - .python-version
      - Dockerfile
      - runpod.dockerfile
      - serverless.py
      - pyproject.toml
      - uv.lock
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    uses: opendreamnet/github-config/.github/workflows/build-docker-image.yml@main
    secrets: inherit
    with:
      environment: development
      docker-file: ./runpod.dockerfile
      runs-on: '"ubuntu-8cores"'
