name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - diffusers_helper/**
      - local_types/**
      - modules/**
      - utils/**
      - .python-version
      - Dockerfile
      - runpod.dockerfile
      - serverless.py
      - pyproject.toml
      - uv.lock
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: production
      runs-on: high-bandwidth
